name: CI/CD Calculator App

on:
  push:
    branches:
      - main

jobs:

  ci:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependency
        run: npm install

      - name: Run Unit Test
        run: npm test

      - name: Build
        run: |
          mkdir dist
          cp app/index.html dist/
          cp app/style.css dist/
          cp app/app.js dist/
          cp app/math.js dist/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-build
          path: dist/

  cd:

    needs: ci

    runs-on: ubuntu-latest

    steps:

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build

      - name: Deploy
        run: |
          echo "Deploy berhasil!"